### ISSUE TITLE
CSLA and WinForms

### ISSUE THREAD

**Issue by sanyo-ok** [MugenMvvmToolkit/MugenMvvmToolkit#16]
Hello,

I was just looking for a "best pattern"  method of binding WinForms controls like DevExpress XtraGrid to nHibernate collections. I did my own code using BindingSource, it works even with multilevel (master/detail) grids - any amount of levels.

I was aware there is better method to build applications using business level frameworks like CSLA.
It also has data binding features even for WinForms:
http://nugetmusthaves.com/Package/CSLA-WindowsForms

Then I read it is a good idea to use a ModelView pattern, especially if used together with XAML based GUI like WPF, UWP, etc. according to "Rockford Lhotka":
http://www.lhotka.net/weblog/WhyMVVM.aspx

They have an adapter for CaliburnMicro and specifically mod for WinForms:
https://github.com/MvvmFx/MvvmFx

Is it possible to use your MugenMvvmToolkit with CSLA and WinForms the same way? 
How much work is needed to make them working together?

Is it a good idea to use following chain of components:
DevExpress WinForms XtragGrid -> MVVM->CSLA->nHibernate 
?
I am reluctant to switch to WPF until MS unveils their plans to make WPF crossplatform at least on Linux

For now DevExpress WinForms works fine on Linux + Wine and I do not have to spend time on learning WPF, look and feel of DevExpress WinForm is ok for me though my DXP license includes WPF too.

**Comment by vyacheslav-volkov** [comment]
Hi there,
Yes it's possible, we used Telerik controls but for some controls you need to write custom attached members (analog of attached properties for WPF), with mugen bindings you can do everything that you can do with control, call methods, set properties, use events etc.
Some samples of attached properties for standard controls:
https://github.com/MugenMvvmToolkit/MugenMvvmToolkit/blob/master/Platforms/MugenMvvmToolkit.WinForms(4.5)/Binding/Modules/PlatformDataBindingModule.cs
If you have any questions you can ask me using [group on Slack](http://www.mugenmvvmtoolkit.com/)
