### ISSUE TITLE
Is MugenMvvmToolkit.Binding works for Universal Windows apps?

### ISSUE THREAD

**Issue by denis-tsv** [MugenMvvmToolkit/MugenMvvmToolkit#17]
I created blank Uniwersal Windows app and added packages MugenMvvmToolkit and MugenMvvmToolkit.Binding.
After that I created simple ViewModel and bind froperty from ViewModel to TextBlock and received XamlParseException

```
An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in Binding.UWP.exe but was not handled in user code

WinRT information: Failed to assign to property 'MugenMvvmToolkit.WinRT.MarkupExtensions.View.Bind'. [Line: 12 Position: 20]

Additional information: The text associated with this error code could not be found.
```

Trere are no MugenMvvmToolkit.Binding samples for Universal Windows apps, so I have a question: does MugenMvvmToolkit.Binding support Universal Windows apps?

**Comment by vyacheslav-volkov** [comment]
Hi there,
It should work but only in debug mode, .NET native breaks the reflection in release mode.
I try to make it work in release mode and I'll try to add samples.

**Comment by vyacheslav-volkov** [comment]
Added support for UWP bindings in 6.5 version.
You should update Default.rd.xml to keep binding members in release mode for example this line will keep all members for Windows.UI.Xaml.Controls namespace:
<Namespace Name="Windows.UI.Xaml.Controls" Dynamic="Required All" />

More info https://msdn.microsoft.com/en-us/library/dn600639(v=vs.110).aspx
