### ISSUE TITLE
Any analog / kind of ReactiveCommand?

### ISSUE THREAD

**Issue by dadhi** [MugenMvvmToolkit/MugenMvvmToolkit#18]
Hello @vvs0205 ,

More like a question,

Is there any analog already or plans to add Rx / (other) based command?

Thanks,
Maksim

**Comment by vyacheslav-volkov** [comment]
Hello Maksim!
The RelayCommand only supports automatic CanExecuteChanged invocation based on PropertyChanged event from view model.
Sample of RelayCommand with observers:

``` csharp
public class MainVm : CloseableViewModel
    {
        #region Fields

        private bool _canExecuteProperty;

        #endregion

        #region Constructors

        public MainVm()
        {
// if you pass current view model (this) as observer to command it will automatically call CanExecute method if any property of view model is changed
            MyCommand = new RelayCommand(Execute, CanExecute, this);
        }

        #endregion

        #region Properties

        public ICommand MyCommand { get; }

        public bool CanExecuteProperty
        {
            get { return _canExecuteProperty; }
            set
            {
                if (value == _canExecuteProperty) return;
                _canExecuteProperty = value;
                OnPropertyChanged();
            }
        }

        #endregion

        #region Methods

        private void Execute()
        {
        }

        private bool CanExecute()
        {
            return CanExecuteProperty;
        }

        #endregion
    }
```

**Comment by dadhi** [comment]
Got it, thanks. 

btw, looked inside RelayCommand and it does reflection Invoke, which may be not good performance wise.

**Comment by vyacheslav-volkov** [comment]
It's optimized as much as possible, if you found any perf bug you can change it and create pull request.
if you about this line
`_weakHandler = ReflectionExtensions.MakeWeakPropertyChangedHandler(this, OnPropertyChangedDelegate)`
it doesn't use reflection to create delegate it only keep command as weak reference to subscribe to  the PropertyChanged event.

**Comment by dadhi** [comment]
Ah, sorry my miss. Was not accustomed to using `func.Invoke()`, expected `func()`.

**Comment by vyacheslav-volkov** [comment]
No problem, it is good that you see potential performance problem.
