### ISSUE TITLE
DataBindingExtension doesn't work with XAML compilation in Xamarin.Forms

### ISSUE THREAD

**Issue by sdebruyn** [MugenMvvmToolkit/MugenMvvmToolkit#19]
When the method `serviceProvider.GetService(typeof(IProvideValueTarget)` is called, it returns different results depending on XAML compilation.

When XAML compilation is enabled, it returns a `SimpleValueTargetProvider`. When XAML compilation is disabled, it returns a `XamlValueTargetProvider`.

The `SimpleValueTargetProvider` is not compatible with the rest of the code in v5.1.

Update: I contacted Xamarin support and will update this issue when I hear back from them.

**Comment by sdebruyn** [comment]
Feedback from Xamarin.Forms team: this is the expected behavior. The code should handle both target providers.
As this is a workaround for `TargetProperty` not being implemented, they updated the bug report about that one too.

**Comment by stefandevo** [comment]
@vvs0205 would it be possible to fix this without xamarin support? We could
Do a PR on the xamforms open source code but also for them it would
Possible break backwards compat.

**Comment by vyacheslav-volkov** [comment]
> @vvs0205 would it be possible to fix this without xamarin support?

Unfortunately no, they generate code using IL and don't pass target property argument
https://github.com/xamarin/Xamarin.Forms/blob/2590d913f7c69f1be60c2c5ac7fb60d0ec8732ed/Xamarin.Forms.Build.Tasks/NodeILExtensions.cs#L413-L428

> Do a PR on the xamforms open source code but also for them it would
> Possible break backwards compat.

If you will add support for TargetProperty it will not break backwards compat.

If you want to use xaml compilation and until xamarin fix this issue I recommend to use Bind extension I fixed it in new version that will be available soon it will work with xaml compilation.

**Comment by stefandevo** [comment]
Ok. Thanks for feedback. I will wait for 6.0 and evaluate further.
