### ISSUE TITLE
Dynamic assemlies cannot be loaded if used in the project

### ISSUE THREAD

**Issue by Dmdv** [MugenMvvmToolkit/MugenMvvmToolkit#21]
In my project I have types which are proxied with Castle.
Castle creates dynamic assembly. 
And if my type is instantiated before the bootstrap starts,
the bootstrapper starts traversing for dynamic assemblies as well and look for local storage location of the dynamic assemlies and the appication crashes.

I've create a pull request to fix it.

**Comment by vyacheslav-volkov** [comment]
Hi there,
Thanks for fix!
