### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by sdebruyn** [MugenMvvmToolkit/MugenMvvmToolkit#22]
You currently can't install Mugen v6 into a project targeting .NET Standard. Probably all you need to change is the nuspec.

**Comment by sdebruyn** [comment]
Can be fixed with #23

**Comment by vyacheslav-volkov** [comment]
will be added in version 6.5

**Comment by alexander-efremov** [comment]
Why 6.5? :) Are you planning to add something big?

2016-10-30 13:48 GMT+07:00, Vyacheslav Volkov notifications@github.com:
