### ISSUE TITLE
Events binding

### ISSUE THREAD

**Issue by Ilchert** [MugenMvvmToolkit/MugenMvvmToolkit#35]
It will be greate, if binding would be able to bind control events to view model methods, like caliburn micro.
Something like this:
`set.Bind(button).Event(p=>(p).DoubleClick+=null).To(() => (vm, ctx) => vm.Select());`
or
`set.Bind(button, p=>p.DoubleClick+=null).To(() => (vm, ctx) => vm.Select());`

**Comment by BrunoVT1992** [comment]
@Ilchert this is already possible:
`set.Bind(button, nameof(button.DoubleClick)).To(() => (vm, ctx) => vm.Select());`

**Comment by Ilchert** [comment]
You are awesome! Do you have any plans to add XML comments to main classes and interfaces?
