### ISSUE TITLE
[winform] How do I enable my user control props for binding?

### ISSUE THREAD

**Issue by Thraka** [MugenMvvmToolkit/MugenMvvmToolkit#36]
I have a custom user control that has a property. What do I need to do to make it usable from the binding  within a view? I'm trying to bind the control.prop to my viewmodel.prop but this doesn't seem to work in twoway:

```csharp
// The bind call in the form
set.Bind(clrBackground, () => clr => clr.Color).To(() => (vm, ctx) => vm.DocumentBackground).TwoWay();
```

```csharp
// The 'Color' property in the user control.
public Microsoft.Xna.Framework.Color Color
{
    get => color;
    set
    {
        color = value;
        picColor.BackColor = value.ToDrawingColor();
    }
}
```

Thank you for any help you can provide.

It seems like a really nice framework, but it's not well documented and caused me hours of frustration to just understand how things work. It would be nice if the sample project demonstrated simple scenarios that everyone must do to essentially learn how the system works.

**Comment by vyacheslav-volkov** [comment]
Hi there, everything is simple if you want to add support for two way bindings, you just need to notify about Color changes you can add event ColorChanged or implement INotifyPropertyChanged for your control:
```csharp
// The 'Color' property in the user control.
public Microsoft.Xna.Framework.Color Color
{
    get => color;
    set
    {
        color = value;
        picColor.BackColor = value.ToDrawingColor();
        ColorChanged?.Invoke(this, EventArgs.Empty);
    }
}

public event EventHandler ColorChanged;
```

**Comment by vyacheslav-volkov** [comment]
you can also check this https://mugenmvvmtoolkit.readme.io/docs/data-binding for more info about bindings

**Comment by Thraka** [comment]
Awesome that works! What if I want to do the same thing but with an existing control where I cannot add the required event handler?

**Comment by vyacheslav-volkov** [comment]
You can add attached event, if there's exist event with different name you can re-register here's example:
Control has SizeChanged event but for Width and Height binding I need WidthChanged and HeightChanged events and I can re-register it with this name.
```csharp
            var sizeChanged = MemberProvider.GetBindingMember(typeof(Control), nameof(Control.SizeChanged), true, false);
            if (sizeChanged != null)
            {
                MemberProvider.Register(typeof(Control), "WidthChanged", sizeChanged, true);
                MemberProvider.Register(typeof(Control), "HeightChanged", sizeChanged, true);
            }
```
if event is more complex you can manually implement attached event for example for DataGridView.SelectedItem I use this event:
```csharp
            AttachedBindingMember.CreateEvent<DataGridView>("SelectedItemChanged", (info, view, arg3) =>
            {
                arg3 = arg3.ToWeakEventListener();
                EventHandler handler = null;
                handler = (sender, args) =>
                {
                    var gridView = (DataGridView)sender;
                    Action<DataGridView, IEventListener, EventHandler> action =
                        (dataGridView, listener, eventHandler) =>
                        {
                            if (!listener.TryHandle(dataGridView, EventArgs.Empty))
                                dataGridView.CurrentCellChanged -= eventHandler;
                        };
                    //To prevent this exception 'Operation not valid because it results in a reentrant call to the SetCurrentCellAddressCore function'
                    gridView.BeginInvoke(action, gridView, arg3, handler);
                };
                view.CurrentCellChanged += handler;
                return WeakActionToken.Create(view, handler,
                    (gridView, eventHandler) => gridView.CurrentCellChanged -= eventHandler);
            });
```

**Comment by BrunoVT1992** [comment]
A more simpler solution is to implement the INotifyPropertyChanged interface in your custom view, for example:

public class CustomView : INotifyPropertyChanged
        {
            public Microsoft.Xna.Framework.Color Color
            {
                get => color;
                set
                {
                    color = value;
                    picColor.BackColor = value.ToDrawingColor();
                    OnPropertyChanged();
                }
            }
            public event PropertyChangedEventHandler PropertyChanged;

            public void OnPropertyChanged([CallerMemberName]string propertyName = null)
            {
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
            }
        }


This will allow the mvvmframework to automatically do twoway bindings

**Comment by Thraka** [comment]
Awesome, thanks!
