### ISSUE TITLE
How do I show a different view for the same viewmodel?

### ISSUE THREAD

**Issue by Thraka** [MugenMvvmToolkit/MugenMvvmToolkit#37]
I have two views that will use the same backing viewmodel, one editing one part of it, the other, a different part. How do I use a command from the viewmodel to force a new popup to appear for a specific view, reusing the viewmodel?

**Comment by Thraka** [comment]
I found the overview article state

```csharp
[ViewModel (typeof (ItemViewModel), "ViewName")]
```

So I added that to the view and I can now correctly show that alternative view. I don't know how to use the same viewmodel instance though when showing it. Or is this the case for the "DataContext" system?

**Comment by vyacheslav-volkov** [comment]
Hi there, as I understand you want to show one ViewModel twice, mugen uses one to one relationship for ViewModel <-> View and if you shown any ViewModel but not closed View you cannot reuse it using ShowAsync method because it can broke navigation (I plan to change this behavior later), but you can just set DataContext for second View and it will work.

**Comment by Thraka** [comment]
Does the DataContext object represent the Model part of **M**VVM ?

**Comment by vyacheslav-volkov** [comment]
not clear for me, what do you mean, DataContext it's usually ViewModel?

**Comment by Thraka** [comment]
In MVVM meaning Model-View-ViewModel. Does the datacontext object represent the **Model** piece? Or is that just your own code itself?

The main docs don't seem to talk much at all about the datacontext, I'm not sure how to use it?

**Comment by vyacheslav-volkov** [comment]
Do you use WPF before? WinForms concept is equivalent to WPF you can read more about this from MS docs https://msdn.microsoft.com/en-us/library/ff798384.aspx.

**Comment by Thraka** [comment]
When using the `DataContext`, do I make my own subclassed version with the properties I need set? Kind of like how the `NavigationContext` object is?

Do you have an example or some psudo code that can show me how to do what I'm trying to do?

**Comment by vyacheslav-volkov** [comment]
Ah you mean DataContext class, no you don't need to subclass it it just like dictionary but with strong types, framework uses it to handle some cases like navigation\view\viewmodel creation parameters etc.
