### ISSUE TITLE
Xamarin.Forms TabbedPage support

### ISSUE THREAD

**Issue by sdebruyn** [MugenMvvmToolkit/MugenMvvmToolkit#39]
Xamarin.Forms has a great TabbedPage which renders to the native tabs and now even supports the bottom tabs on Android. How can I use this with a MultiViewModel? I tried to do this, but then the app navigates *out* of the tabs instead of keeping the navigation inside the tab.

**Comment by vyacheslav-volkov** [comment]
Hi @SamuelDebruyn!

Which type of navigation do you want, can you provide more context. 
For example you can change `SelectedItem` property or use `DynamicMultiViewModelPresenter` that will support `ShowAsync` method or you can add custom presenter.

**Comment by vyacheslav-volkov** [comment]
or maybe do you want `NavigationPage` inside Tab?

**Comment by stefandevo** [comment]
Using a NavigationPage inside of each Tab, so that you have multiple hierarchies of navigation, and then a way to navigate from a viewModel inside a specific tab. First case is indeed Xamarin Forms, but would be great if this would work if using Xamarin.iOS and Xamarin.Android directly.

**Comment by vyacheslav-volkov** [comment]
I added sample with some notes that will use custom presenter to do this, let me know if you have any questions.

[MugenMvvm.TabbedPage.zip](https://github.com/MugenMvvmToolkit/MugenMvvmToolkit/files/2252799/MugenMvvm.TabbedPage.zip)

**Comment by sdebruyn** [comment]
Thanks, exactly what I needed!
