### ISSUE TITLE
Questions: More samples available?

### ISSUE THREAD

**Issue by stefandevo** [MugenMvvmToolkit/MugenMvvmToolkit#4]
Hi I came along this fine library.
As I am evaluating different mvvm libraries, I would like to know if you have samples of:
- xamforms using master/detail, tabview
- use of android fragments

thx

**Comment by vyacheslav-volkov** [comment]
Hi there,
- Unfortunately I do not have an example for xamforms using master/detail.
- XamarinForms [tabview sample](https://github.com/MugenMvvmToolkit/MugenMvvmToolkit.Samples/tree/master/MugenMvvmToolkit.Samples.Navigation/Navigation).
- Android [fragments for tabview sample](https://github.com/MugenMvvmToolkit/MugenMvvmToolkit.Samples/blob/master/MugenMvvmToolkit.Api.Android/ApiExamples.AppCompat/Views/Tabs/TabLayoutActivityView.cs) and [fragments for content with backstack sample](https://github.com/MugenMvvmToolkit/MugenMvvmToolkit.Samples/blob/master/MugenMvvmToolkit.Api.Android/ApiExamples/Views/Fragments/BackStackFragmetActivityView.cs)

If you have additional questions, I will gladly answer.

**Comment by stefandevo** [comment]
Ok thanks for your quick reply! I'll look into the provided samples.

**Comment by stefandevo** [comment]
Hi,
Is it possible to support a master/detail kind of app, or for example split-view ipad app, or android with left drawer menu with this toolkit?

**Comment by vyacheslav-volkov** [comment]
Yes, of course, later I will add an example and give you a link.

**Comment by stefandevo** [comment]
A small beginner's guide would be nice :-)

**Comment by stefandevo** [comment]
Would it be an idea to create a Slack group so that people are able to discuss/chat about this framework and together with you get some support? Let me know, and I'll set it up! (or any other chat/support something)

**Comment by vyacheslav-volkov** [comment]
Later I'll try to write a little 'getting started' guide.
The group is a good idea, if you help me set it up it will be fine :)

**Comment by stefandevo** [comment]
OK, working on that one. Could you send me an email to discuss further?
stefan.de.vogelaere at gmail.com
