### ISSUE TITLE
Opening new windows not as child windows

### ISSUE THREAD

**Issue by SKProCH** [MugenMvvmToolkit/MugenMvvmToolkit#45]
If I try to open a window as stated in the documentation:
```csharp
using (var myVm = GetViewModel<MyVm>()) {
    await myVm.ShowAsync();
}
```
That window opens as a child window. What's the best way to avoid this?  
P.S. My goal is to close the previous window before opening a new one

----
Apparently, the method `ShowAsync()` blocks thread in any case, even if you do not use `await`. Is that what you intended?

**Comment by vyacheslav-volkov** [comment]
Hi, you need to use hint parameter `NavigationConstants.IsDialog`, here's example:
```csharp
using (var myVm = GetViewModel<MyVm>()) {
    await myVm.ShowAsync(NavigationConstants.IsDialog.ToValue(false));
}
```

>Apparently, the method ShowAsync() blocks thread in any case, even if you do not use await. Is that what you intended?

this is default behavior if you'll use `Window.ShowDialog` method.

**Comment by SKProCH** [comment]
Oh, so this is how it works. Thanks
