### ISSUE TITLE
LocalizableResources not working on Android

### ISSUE THREAD

**Issue by stefandevo** [MugenMvvmToolkit/MugenMvvmToolkit#6]
As per our http://mugenmvvmtoolkit.slack.com discussion, there is something broken on Android regarding to translations.

```
LocalizableResources.ResourceManager.GetString(member, LocalizableResources.Culture)
```

does not work anymore.

**Comment by vyacheslav-volkov** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=31720
http://forums.xamarin.com/discussion/44745/localization-on-android-via-todolocalized-example-not-working#latest
