### ISSUE TITLE
UWP Splitview navigation sample

### ISSUE THREAD

**Issue by binoypatel** [MugenMvvmToolkit/MugenMvvmToolkit#7]
Hi Vyacheslav

First of all, congratulation for making Mugen mvvm framework, I have just started exploring it and found really good. One thing that I couldn't find is how to implement custom navigation? For example, on Windows 10 UWP app I am using SplitView and I don't know how to glue navigation from Mugen that can directly interact with Frame navigation. Do you have any sample that shows how to do that?

Kind regards,
Binoy

**Comment by vyacheslav-volkov** [comment]
Hi Binoy,

I made an example for you https://onedrive.live.com/redir?resid=F99688C1115B37F5!7250&authkey=!AFikg9Q7gmexHhs&ithint=folder%2czip, later I will add this example to the main examples.
I hope this helps.

**Comment by binoypatel** [comment]
Hi Vyacheslav

Thank you so much for your prompt help. I now understand the framework better. Your example helped me lot. 

Kind regards,
Binoy
